  spring:
    application:
      name: E-medical

    datasource:
      url: jdbc:postgresql://localhost:54320/e_medical
      username: postgres
      password: passer@123
      driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          id:
            new_generator_mappings: true
          jdbc:
            lob:
              non_contextual_creation: true


  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 3600000  # 1h en millisecondes



  server:
    port: 8081

  logging:
    level:
      org:
        springdoc: DEBUG
        springframework:
          web: DEBUG
        hibernate: ERROR


